import { useEffect, useState } from 'react';
import { getDashboard } from '../services/interviewApi';

const metricMeta = [
  ['Tamamlanan görüşme', '◌', 'toplam'], ['Ortalama puan', '↗', 'ortalama'], ['En yüksek puan', '★', 'en-iyi'], ['En düşük puan', '◔', 'en-düşük']
];

export default function Dashboard({ onStart, onHistory }) {
  const [data, setData] = useState(null);
  useEffect(() => { getDashboard().then(setData).catch(() => setData({ error: true })); }, []);
  if (!data) return <main className="dashboard-page"><div className="dashboard-loading">Performans verileri hazırlanıyor…</div></main>;
  if (data.error) return <main className="dashboard-page"><div className="dashboard-loading error">Dashboard verisi alınamadı.</div></main>;
  const values = [data.totalInterviewsCompleted, `${data.averageInterviewScore}/100`, data.highestScore, data.lowestScore];
  const trend = data.scoreHistory.length > 1 ? data.scoreHistory.at(-1).score - data.scoreHistory.at(-2).score : 0;
  return <main className="dashboard-page"><header className="dashboard-hero"><div><p className="eyebrow">Gelişim dashboardu</p><h1>Teknik görüşme<br />performansın</h1><p>Sonuçlarını izle, güçlü konularını koru ve gelişim alanlarını hedefle.</p></div><div className="dashboard-actions"><button className="dashboard-ghost" onClick={onHistory}>Geçmişi görüntüle</button><button className="dashboard-primary" onClick={onStart}>Yeni görüşme <span>→</span></button></div></header><section className="metric-grid">{metricMeta.map(([label, icon, tone], index) => <article className={`metric-card ${tone}`} key={label}><span className="metric-icon">{icon}</span><span className="metric-label">{label}</span><strong>{values[index]}</strong>{index === 1 && <small className={trend >= 0 ? 'positive' : 'negative'}>{trend >= 0 ? '↗' : '↘'} Son görüşmeye göre {Math.abs(trend)} puan</small>}</article>)}</section><section className="dashboard-panel score-panel"><div className="panel-heading"><div><p className="eyebrow">İlerleme</p><h2>Puan geçmişi</h2></div><span className="panel-chip">{data.scoreHistory.length} görüşme</span></div>{data.scoreHistory.length ? <div className="history-chart">{data.scoreHistory.map((item, i) => <div className="history-column" key={`${item.completedAtUtc}-${i}`}><div className="history-value">{item.score}</div><div className="history-bar-wrap"><div className="history-bar" style={{ height: `${Math.max(item.score, 5)}%` }} /></div><small>{item.topic}</small></div>)}</div> : <p className="empty-state">İlk grafiğini görmek için bir görüşmeyi tamamla.</p>}</section><section className="dashboard-panel"><div className="panel-heading"><div><p className="eyebrow">Alan analizi</p><h2>Konu performansı</h2></div><span className="panel-chip">Hedef: 80+</span></div>{data.topicPerformance.length ? <div className="performance-list">{data.topicPerformance.map(item => <div className="performance-row" key={item.topic}><div className="performance-label"><strong>{item.topic}</strong><span>{item.interviewCount} görüşme</span></div><div className="performance-track"><i style={{ width: `${item.averageScore}%` }} /></div><b>{item.averageScore}</b></div>)}</div> : <p className="empty-state">Konu analizi için tamamlanan görüşmeler gerekli.</p>}</section></main>;
}
